### ISSUE TITLE
Plans for an R package

### ISSUE THREAD

**Issue by alexpghayes** [zinka88/Fair-Regression#1]
This looks super cool! Are there any plans to wrap these new methods into an R package to make it easy to apply them in other research projects?

**Comment by sherrirose** [comment]
Thanks for the question. Our paper leveraged the existing CVXR R package by Stanford PhD student Anqi Fu and her collaborators: cvxr.rbind.io

Their package allows the flexible specification of novel constraints and penalties for new methods!

Watch Anqi's useR! 2018 conference presentation about CVXR: www.youtube.com/watch?v=MyglbtnmQ8A
